### ISSUE TITLE
Importing @tailwindcss/utilities in CSS file causes ENOBUFS error

### ISSUE THREAD

**Issue by davidhao3300** [nvh95/jest-preview#260]
## Describe the bug

Hello, me again.

The CSS transformer errors out with ENOBUFS with the following CSS file contents:

```
@import 'tailwindcss/utilities';
```

We use tailwindcss 1.9.6 if that helps, my suspicion is that it's just a large CSS file or something.

The full error:

```
  ● Test suite failed to run                                                                                                                         [110/1363]

    spawnSync node ENOBUFS

      at processPostCss (node_modules/jest-preview/transforms/css.js:254:34)
      at processCss (node_modules/jest-preview/transforms/css.js:114:16)
      at Object.process$1 [as process] (node_modules/jest-preview/transforms/css.js:371:12)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

Corresponds to https://github.com/nvh95/jest-preview/blob/main/src/transform.ts#L356

I changed the erroring line to
`const result = child_process.spawnSync('node', [tempFileName], {maxBuffer: 10 * 1024 * 1024});`, which works. The maxBuffer default is 1MB or something, and not sure what you want the actual value to be.

## Expected behavior

No error to occur

**Comment by nvh95** [comment]
Hi @davidhao3300 

Thanks for reporting this. Can you help to prepare a reproduction? It's hard for me to fix this without properly reproducing this. Thanks.

**Comment by davidhao3300** [comment]
I'm not a frontend expert, so this is my guess to a repro:
- Have tailwindcss@1.9.6 installed
- Have a single css file with `@import 'tailwindcss/utilities';` as the contents
- include the CSS file and have it transformed by the jest-preview CSS transformer

**Comment by ilankleingong** [comment]
hi, I am now getting this issue on my less local files, which are big
any chance to get a new version with the buffer fix?
